### ISSUE TITLE
Implementació del joc en Phaser.io

### ISSUE THREAD

**Issue by u1975104** [ArtEnjoyers/artists-vs-cryptos#4]

**Comment by enricbesora** [comment]
El joc esta fet principalment, els errors coneguts son:
- Pots posar mes d'una unitat al mateix lloc
- Si surt un enemic i a la vegada poses una unitat el joc dona un error raro i poses un enemic que no es mou
- A vegades si surt un enemic i plantes se't gasta l'energia pero no poses res
- El joc es reincia al posar tots els enemics, no al matarlos.

**Comment by enricbesora** [comment]
El joc ja no es reinicia tant rapid.

**Comment by enricbesora** [comment]
Els errors coneguts son per culpa del propi motor del joc, al spawnejar 2 coses a la vegada a vegades dona error, pero esta tot acabat.
